### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by sphereinabox** [hudbrog/gCodeViewer#29]
Hey, I just like to make sure my little fork is OK but I don't see a license file here. It looks like this is licensed Creative Commons Attribution at http://www.thingiverse.com/thing:35248 but I don't see a license in the README or a LICENSE file here on GitHub.

Please add an explicitly named license.

Thanks!

**Comment by hudbrog** [comment]
Thanks! You are right, for some reason I did forget to include a LICENSE file. Fixed that.
