### ISSUE TITLE
gcode.ws domain expired

### ISSUE THREAD

**Issue by helaan** [hudbrog/gCodeViewer#74]
Currently the domain is showing a parking page from GoDaddy with the following message:

```
NOTICE: This domain name expired on 2/12/2019 and is pending renewal or deletion.
```

Are there any plans to keep the site online?

**Comment by Moorviper** [comment]
it is up again -> can be closed

**Comment by hudbrog** [comment]
Thanks for the notice. Was out of the country with limited access to internet and kinda forgot about it =)
