### ISSUE TITLE
Doesn't process sources running locally on FF

### ISSUE THREAD

**Issue by Farbhead** [hudbrog/gCodeViewer#90]
Running the gCodeViewer on my local computer doesn't seem to work.  I can browse and select a gcode file, and I can see the gcode in the GCode tab, but the progress indicators don't advance.  Running online gCodeViewer seems to be functional (I haven't kicked the tires yet) in same FF browser.

Steps taken:
downloaded master branch using "Download Zip" option
extracted zip to local directory
opened index.html in FF browser
loaded gcode file using Browse... button
checked GCode tab and I can see the source there
checked progress indicators and they are at 0%

![image](https://user-images.githubusercontent.com/94203858/141596280-294a899a-2390-4c25-94fd-68b546fa8144.png)

opened the Browser Console & saw these error messages:

![image](https://user-images.githubusercontent.com/94203858/141596346-1683e36a-f67c-46fc-9bbf-4ecf6dd93c4a.png)

I am on a Windows 10 Pro machine (build 19042.1348) with 16GB of RAM

I am running this version of FF browser:

![image](https://user-images.githubusercontent.com/94203858/141596847-81355401-5a78-4cc8-9fc5-12916e166902.png)

**Comment by hudbrog** [comment]
In Firefox, first you need to navigate to about:config in the Firefox browser, search for the privacy.file_unique_origin setting, and set it from true to false by double-clicking it. 

This is super non-secure, so it's really better not to do it and use online version instead.
